### ISSUE TITLE
Use CMAKE_AUTOUIC

### ISSUE THREAD

**Issue by dimitry-ishenko** [ynonp/qt-widgets-template#1]
https://github.com/ynonp/qt-widgets-template/blob/2d2de6073e4b8f630a67ff0a6f38e5682f305761/CMakeLists.txt#L21

Using `qt5_wrap_ui` is so yesterday. Use `set(CMAKE_AUTOUIC ON)` instead.

**Comment by ynonp** [comment]
Looks cool - care to put it in a Pull Request?

**Comment by dimitry-ishenko** [comment]
Nope. Just figured you should know

**Comment by ynonp** [comment]
Thanks for the update, will check it out :)
